Fix compile error when --lean-and-mean is set
The enum ndCR_OPTION_DISABLED should be ndCR_DISABLED_OPTION.

nd-instance.cpp:642:20: error: 'ndCR_OPTION_DISABLED' was not declared in this scope
  642 |             return ndCR_OPTION_DISABLED;
      |                    ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>